### ISSUE TITLE
v2 api not working

### ISSUE THREAD

**Issue by retoo** [jenkinsci/hipchat-plugin#38]
i get the error:

```
WARNING: HipChat post may have failed. ResponseCode: 401, Response: {
  "error": {
    "code": 401,
    "message": "Invalid OAuth session",
    "type": "Unauthorized"
  }
}
```

v1 is working without troubles. Do I have to configure a different token?

**Comment by aldaris** [comment]
As the readme says: v1 requires an auth_token, v2 requires an access_token instead. You should follow https://www.hipchat.com/docs/apiv2/auth to obtain your token.

**Comment by retoo** [comment]
thanks, my fault

**Comment by markstos** [comment]
I'm noting for this historical record that the HipChat v1 API is deprecated: https://confluence.atlassian.com/hipchatkb/what-are-the-differences-between-hipchat-api-v1-and-v2-tokens-847750664.html

For ther people who this find this page, the recommended action is not to return to using v1 because it seems to work, it's to move forward with getting a v2 token.
