### ISSUE TITLE
Jenkins Behind Proxy

### ISSUE THREAD

**Issue by ebrahim-moshaya** [jenkinsci/hipchat-plugin#57]
I am having issues in that I have Jenkins running behind a proxy server. I've configured Jenkins based on the following link:
https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy

However, I'm having issues with configuring this plugin to bypass proxy or use the proxy settings in the link above... Please see screenshot attached
![screenshot](https://cloud.githubusercontent.com/assets/8818542/10601830/3e6c7fc0-770c-11e5-8830-193568409032.jpg)

**Comment by aldaris** [comment]
Which version of the plugin are you using?
I suppose the simplest workaround would be to ensure that the DNS is configured for the Jenkins node, so that it can resolve serviceoperations.hipchat.com. I'm not really sure whether a Java HTTP client needs to be able to resolve the final URL even if a forward proxy is being used...
http://serverfault.com/questions/169816/how-dns-lookups-work-when-using-an-http-proxy-or-not-in-ie suggests that theoretically only the proxy should perform DNS lookups...

If you could attach log snippets or a screenshot of your proxy configuration, that would be appreciated.

**Comment by ebrahim-moshaya** [comment]
I resolved it in the end
