### ISSUE TITLE
"Build successful" not enabled using Job DSL plugin

### ISSUE THREAD

**Issue by ryanerato** [jenkinsci/hipchat-plugin#64]
I'm using the Jobs DSL plugin ([https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin]) to generate many other jobs of ours. Following the documentation of that plugin ([https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.hipChat]) I want HipChat notifications enabled for successful, failed, and aborted builds. The latter two options are added and enabled, but the "successful" notification is added, but not enabled. I attached images from the config pages for both jobs (the generator and the generated). I haven't noticed anything in the logs that would indicated an issue, but I could've missed something.

![screen shot 2016-01-15 at 2 10 36 pm](https://cloud.githubusercontent.com/assets/913753/12366823/833f071a-bb92-11e5-827b-c21e6490fe54.png)

![screen shot 2016-01-15 at 2 11 35 pm](https://cloud.githubusercontent.com/assets/913753/12366826/8705beca-bb92-11e5-9628-94c1a98dcaf9.png)

**Comment by aldaris** [comment]
This is expected behavior.
Firstly the Notify Room column is about whether the HipChat room should be notified (with a visible card and notification sound). Secondly by default only notifications that have non-green color associated will notify the room.
I think you are running into this behavior because the config is now stored differently since the 1.0.0 release (previously there was no notify room option), so what is probably happennig is that this DSL plugin creates the config in the old format, and then this old-style config is converted into the new style config by the plugin, which for backwards compatibility reasons will follow the exact same logic when determining notification color and notify room fields based on the notification type.

I think you should ask the DSL plugin's maintainer to update the HipChat integration to work with the new configuration structure.

**Comment by ryanerato** [comment]
Interesting that it works for the other notification types I have specified, only "successful" doesn't work. The Job DSL wiki page merely linked to the HipChat Plugin page, so I assumed the plugin owner had to enable support for DSL, but that seems to not be the case.

Thanks for the quick response, I'll let the Job DSL team know, it seems they're still referencing a < 1.0 version of the HipChat plugin.

**Comment by aldaris** [comment]
It should be the same with Started notifications as well, in the previous version only those two were associated with green notification color (and those never triggered room notifications), see [code](https://github.com/jenkinsci/hipchat-plugin/blob/hipchat-0.2.0/src/main/java/jenkins/plugins/hipchat/NotificationType.java)

**Comment by deeptik2** [comment]
Has this been fixed?
